//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.19 at 12:23:34 PM CET
//


package br.com.spring.integration.types;

import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "atualizarUsuario")
@XmlType(name = "atualizarUsuario",
        propOrder = {"usuario"})
public class UserRequest {

    @XmlAttribute(name = "nome", required = true)
    protected String nome = "Hello!";

    @XmlElement(required = true)
    protected User usuario;


    public UserRequest() {
    }

    public UserRequest(User usuario) {
        this.usuario = usuario;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public User getUsuario() {
        return usuario;
    }

    public void setUsuario(User usuario) {
        this.usuario = usuario;
    }

    @Override
    public String toString() {
        return "UserRequest{" +
                "nome='" + nome + '\'' +
                ", usuario=" + usuario +
                '}';
    }
}
